services:
  testDB:
    image: postgres:13-alpine
    container_name: testDB
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    
  api:
    depends_on:
      - testDB
    env_file:
      - .env.test
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@testDB:5432/test?connect_timeout=300&schema=public
    