services:
  testDB:
    image: postgres:13-alpine
    container_name: testDB
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  api:
    depends_on:
      testDB:
        condition: service_healthy
    env_file:
      - .env.test
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@testDB:5432/test?connect_timeout=300&schema=public
    