

services:
  testDB:
    image: postgres:13-alpine
    container_name: testDB
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    depends_on:
      - api
  api:
    env_file:
      - .env.test
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@testDB:5435/test?schema=public
    