version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    volumes:
      - cache:/data
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=oneblue
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    container_name: api
    build:
      context: .
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/usr/app
      - /usr/app/node_modules

volumes:
  cache:
  pgdata: